'use strict';

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

// Load signature rules once at module load time
const signaturesPath = path.join(__dirname, 'signatures.yml');
const signatures = yaml.load(fs.readFileSync(signaturesPath, 'utf8'));

/**
 * Redacts JWT tokens and Bearer tokens (PII) from log content.
 * @param {string} content - Raw log content
 * @returns {string} Redacted log content
 */
function redactPii(content) {
  if (!content) return content;
  // Redact JWT tokens: three base64url segments separated by dots
  let redacted = content.replace(
    /eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]*/g,
    '[JWT_REDACTED]'
  );
  // Redact Bearer tokens
  redacted = redacted.replace(/Bearer\s+[a-zA-Z0-9._\-+/=]+/gi, 'Bearer [TOKEN_REDACTED]');
  return redacted;
}

/**
 * Extracts log content from Markdown code fences in the issue body.
 * Falls back to text after a "Logs:" heading when no fences are found.
 * @param {string} issueBody - GitHub issue body
 * @returns {string[]} Array of extracted log blocks
 */
function extractLogBlocks(issueBody) {
  if (!issueBody) return [];
  const blocks = [];

  // Match ``` code fences with an optional language specifier
  const fenceRegex = /```(?:log|text|plaintext)?\s*\n([\s\S]*?)```/gi;
  let match;
  while ((match = fenceRegex.exec(issueBody)) !== null) {
    blocks.push(match[1]);
  }

  // Fallback: content after a "Logs:" or "MSAL Logs:" heading
  if (blocks.length === 0) {
    const headingMatch = issueBody.match(/(?:MSAL\s+)?Logs?:\s*\n([\s\S]+)/i);
    if (headingMatch) {
      blocks.push(headingMatch[1]);
    }
  }

  return blocks;
}

/**
 * Determines whether the log content originates from an MSI v2 flow.
 * @param {string} logContent - Combined log text
 * @returns {boolean}
 */
function isMiV2Log(logContent) {
  if (!logContent) return false;
  return signatures.stages.mi_v2_flow.patterns.some(pattern =>
    new RegExp(pattern, 'i').test(logContent)
  );
}

/**
 * Scans log content and returns every pipeline stage whose patterns match.
 * @param {string} logContent - Log text to analyse
 * @returns {Array<{stage: string, label: string, description: string, severity: string, matches: string[]}>}
 */
function detectStages(logContent) {
  if (!logContent) return [];
  const detected = [];

  for (const [stageKey, stage] of Object.entries(signatures.stages)) {
    if (stageKey === 'mi_v2_flow') continue;

    const matchedLines = [];
    const lines = logContent.split('\n');

    for (const pattern of stage.patterns) {
      const regex = new RegExp(pattern, 'i');
      for (const line of lines) {
        if (regex.test(line)) {
          matchedLines.push(line.trim());
        }
      }
    }

    if (matchedLines.length > 0) {
      // Deduplicate and cap at 5 representative lines
      const unique = [...new Set(matchedLines)].slice(0, 5);
      detected.push({
        stage: stageKey,
        label: stage.label,
        description: stage.description,
        severity: stage.severity,
        matches: unique,
      });
    }
  }

  return detected;
}

/**
 * Builds a Markdown comment body for posting on a GitHub issue.
 * Returns null when the result is not from an MSI v2 flow.
 * @param {{isMiV2: boolean, stages: Array}} result
 * @returns {string|null}
 */
function formatComment(result) {
  if (!result || !result.isMiV2) return null;

  const lines = [
    '<!-- msal-log-triage-bot -->',
    '## 🔍 MSI v2 Automated Log Triage',
    '',
    '> *Automated analysis of MSAL logs to identify which pipeline stage failed.*',
    '',
  ];

  if (!result.stages || result.stages.length === 0) {
    lines.push('✅ No specific failure patterns detected in the provided logs.');
    lines.push('');
    lines.push(
      'The logs appear to be from an MSI v2 flow, but no known failure signatures were matched.'
    );
  } else {
    lines.push('### Detected Failure Stages');
    lines.push('');

    const severityEmoji = { error: '🔴', warning: '🟡', info: '🔵' };

    for (const stage of result.stages) {
      const emoji = severityEmoji[stage.severity] || '⚪';
      lines.push(`#### ${emoji} ${stage.label}`);
      lines.push(`> ${stage.description}`);
      lines.push('');
      lines.push('<details>');
      lines.push('<summary>Matched log lines</summary>');
      lines.push('');
      lines.push('```');
      for (const line of stage.matches) {
        lines.push(line);
      }
      lines.push('```');
      lines.push('</details>');
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(
    '*Generated by the MSI v2 Log Triage bot · [View source](.github/msal-log-triage/index.js)*'
  );

  return lines.join('\n');
}

/**
 * Entry point: analyses a GitHub issue body and returns a triage result.
 * @param {string} issueBody - Full issue body text
 * @returns {{isMiV2: boolean, stages: Array, comment: string|null, labels: string[]}}
 */
function analyze(issueBody) {
  if (!issueBody) {
    return { isMiV2: false, stages: [], comment: null, labels: [] };
  }

  // Combine the full body with any explicitly fenced log blocks
  const logBlocks = extractLogBlocks(issueBody);
  const combined = [issueBody, ...logBlocks].join('\n');

  // Redact PII before any pattern matching
  const redacted = redactPii(combined);

  if (!isMiV2Log(redacted)) {
    return { isMiV2: false, stages: [], comment: null, labels: [] };
  }

  const stages = detectStages(redacted);
  const comment = formatComment({ isMiV2: true, stages });

  const labels = ['msi-v2:triage-run'];
  if (stages.some(s => s.severity === 'error')) {
    labels.push('msi-v2:has-failure');
  }

  return { isMiV2: true, stages, comment, labels };
}

module.exports = { analyze, redactPii, extractLogBlocks, isMiV2Log, detectStages, formatComment };
